services:
  - type: web
    name: mytra-1
    runtime: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    workingDir: backend    # Burada backend klasörünü root olarak gösteriyoruz
    autoDeployTrigger: commit
    plan: free
