services:
  - type: web
    name: mytra-root-app
    env: python
    workingDir: /
    startCommand: gunicorn app:app
    # port, plan, vs. buraya...

  - type: web
    name: mytra-backend-app
    env: python
    workingDir: backend
    startCommand: gunicorn app:app
    # farklı port ataman lazım, örn: 5001 gibi
